### ISSUE TITLE
get_B1740 returns no content

### ISSUE THREAD

**Issue by Carterbouley** [OSUKED/ElexonDataPortal#8]
Hi

Thanks for building this - its very helpful. However i have found two requests do not return any information, namely B1740 and  B1750. 

Is this an issue with elexon itself or the package, and do you know of any workounds?

Thanks

**Comment by AyrtonB** [comment]
Hi @Carterbouley, no worries, I'm glad its been helpful.

Could you post the code you used (without the API key) as well as the error please, this will help me diagnose what's happening.

**Comment by novomurchu** [comment]
Hey @AyrtonB, firstly, terrific work here. 
Just revisiting the original comment above, I've found that polling B1740, B1750, B1760 are returning empty DataFrames. 

```
from ElexonDataPortal import api
client = api.Client('myapi')

start_date  = '2023-05-01'
end_date    = '2023-05-02'
NGCBMUnitID = 'ANSUW-1' 

df_B1610 = client.get_B1610(start_date, end_date,NGCBMUnitID)
df_B1760 = client.get_B1760(start_date, end_date)
```

error/warning raised:
 warn(f'Data request was succesful but no content was returned')
